10-10-Make a console out
KUL-Java/RPG-MAKER pull request #7
Opened 2019-12-22 18:18 UTC by PawelPaziewski

I wait for your code review.

2019-12-22 18:51 UTC, Dandoo1212 requested changes

2019-12-22 18:51 UTC, Dandoo1212 commented on src/main/java/ConsoleOut/ColorCoder.java
> +    BLACK("\u001B[30m"), RED("\u001B[31m"), GREEN("\u001B[32m"), YELLOW("\u001B[33m"), BLUE("\u001B[34m"), PURPLE("\u001B[35m"), WHITE("\u001B[37m"),CYAN("\u001B[36m");
Formatting! (I forgot to mention that we should use google formatter)

2019-12-22 18:51 UTC, Dandoo1212 commented on src/main/java/ConsoleOut/ConsoleOut.java
> +        this.waysWriter = new WaysWriter();
You can't test this. We shouldn't use new Keyword.

2019-12-22 18:51 UTC, Dandoo1212 commented on src/main/java/ConsoleOut/ConsoleOut.java
> +}
This class has 19 lines of code, text writer has 15 and ways writer has 19. I think that this granularity is not good in here. Methods from text and ways writers can be in this class ( private methods).

2019-12-22 18:51 UTC, Dandoo1212 commented on src/main/java/ConsoleOut/ConsoleOut.java
> +        waysWriter.Write(history.getWays(), delay, color);
Methods names should be in lowerCase

2019-12-22 18:51 UTC, Dandoo1212 commented on src/main/java/ConsoleOut/WaysWriter.java
> +        for(Entry<Character, Way> entry:entrySet){
Unnecessary Set. You can iterate directly on ways.entrySet();

2020-01-08 15:52 UTC, Dandoo1212 commented on src/main/java/ConsoleOut/ConsoleOut.java
> +        for (char c : text.toCharArray()) {
If You want, try to learn something about streams in Java (collection streams) and replace this for each loop with a stream, or a for each with lamba ;)

2020-01-08 16:07 UTC, Dandoo1212 commented on src/main/java/pl/rpg/console/ConsoleOut.java
> +public class ConsoleOut implements UserWriter {
Does your code compile?

2020-01-08 16:35 UTC, PawelPaziewski commented on src/main/java/pl/rpg/console/ConsoleOut.java
> +public class ConsoleOut implements UserWriter {
Yes, it is

2020-01-16 12:40 UTC, Dandoo1212 approved these changes

2020-01-16 12:58 UTC, merged